version: '3.8'
services:
  backend:
    build: 
      context: ./backend/toy_shop
    command: bash -c 
      "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000" 
    restart: always
    volumes:
      - ./backend/toy_shop:/usr/src/backend
      - media:/usr/src/backend/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    command: npm run dev 
    restart: always
    volumes:
      - ./frontend/:/usr/src/frontend
      - /usr/src/frontend/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
  media:

