version: '3.8'
services:
  nginx_web_server:
    image: nginx:1.23-alpine-slim
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
     - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    build: 
      context: ./backend/toy_shop
    command: bash -c 
      "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --no-input
      && gunicorn toy_shop.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./backend/toy_shop:/usr/src/backend
      - static:/usr/src/backend/static
      - media:/usr/src/backend/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    image: frontend
    command: bash -c "npm run build && npm run start"
    volumes:
      - ./frontend/:/usr/src/frontend
      - /usr/src/frontend/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

volumes:
  postgres_data:
  static:
  media: